### ISSUE TITLE
Allow the "-l" option to be used when running cmatrix not in console - feature request

### ISSUE THREAD

**Issue by ghost** [abishekvashok/cmatrix#1]
When not in console and running "cmatrix" with the "-l" one gets this error:

```
Couldn't get a file descriptor referring to the console
```

But I would really like to be able to run it with the "-l" option in order to get that cool matrix style font without getting that error. So I think that something should be changed in cmatrix to allow this, such as converting the font to an X font and then making cmatrix use this font when it is run using the "-l" option outside of the console.

**Comment by ik0r** [comment]
sorry @SeventhSonOfASeventhSon this is just a source code mirror, I'm not very familiar with C, so I can't help.

**Comment by ghost** [comment]
@Treri, Oh, so where would be a better place then to suggest this feature?

**Comment by ik0r** [comment]
@SeventhSonOfASeventhSon http://www.asty.org/cmatrix/

**Comment by abishekvashok** [comment]
The error is because the fonts come in conflicts with your fonts outside the console (mostly, in a terminal) and that's why it's happening. If you really want I would try a workaround.

**Comment by abishekvashok** [comment]
@SeventhSonOfASeventhSon -l requires you have consolechars and you run it in a console. So, theres nothing we can do about it except that you change the font preferences and run the matrix font.
