### ISSUE TITLE
autoconf error

### ISSUE THREAD

**Issue by Gwlanbzh** [abishekvashok/cmatrix#100]
When I type `autoconf ./configure.ac', I get these errors at the end of the output:
```
configure.ac:5: error: possibly undefined macro: AM_CONFIG_HEADER
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:6: error: possibly undefined macro: AM_INIT_AUTOMAKE
configure.ac:135: error: possibly undefined macro: AM_CONDITIONAL
```
Why ? (I am a noob with compilation)

**Comment by yikerman** [comment]
Met this issue too. Can be easily solved with https://unix.stackexchange.com/questions/18673/some-m4-macros-dont-seem-to-be-defined.
Also https://github.com/VowpalWabbit/vowpal_wabbit/issues/969.

**Comment by space-pagan** [comment]
Installation instructions in README.md specify

> Using configure (recommended for most linux user)
> 
> ```
> autoreconf -i  # skip if using released tarball
> ./configure
> make
> make install```

`autoreconf -i` and `autoconf ./configure.ac` do different things. Please use the compilation commands as instructed.
@abishekvashok this should be closed
