### ISSUE TITLE
ops seen the R key was for xmas lights. cool feature thanks for this cool cmatrix, happy holidays

### ISSUE THREAD

**Issue by keithsavage777** [abishekvashok/cmatrix#115]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by space-pagan** [comment]
@keithsavage777 There was no need to open an issue ticket for this. @abishekvashok Please close it.

**Comment by abishekvashok** [comment]
> ops seen the R key was for xmas lights. cool feature thanks for this cool cmatrix, happy holidays

cool. Would have appreciated this not if it were not an issue. anyway closing
