### ISSUE TITLE
Add screenshots and improve readme

### ISSUE THREAD

**Issue by abishekvashok** [abishekvashok/cmatrix#12]
Readme file could be improved by:
- [x] Adding screenshots
- [x] Adding additional documentation

Any other suggestion as welcome :)
If you would like to work on this, please comment.

**Comment by hoijui** [comment]
i made a small script to generate screenshots and screencasts (from within X).
see pull request https://github.com/abishekvashok/cmatrix/pull/22

**Comment by abishekvashok** [comment]
Fixed in #22 with 0cc3b1834fc7630762b423251b3cbd38de2b86bf
