### ISSUE TITLE
segfault bug strikes again

### ISSUE THREAD

**Issue by Cristo-Conklin** [abishekvashok/cmatrix#121]
**Describe the bug**
segfault bug strikes again. need a red pill.

**To Reproduce**
Steps to reproduce the behavior (wont happen always):
open several tabs of Fedora33 terminal. (using X desktop, cinnamon)
switch between them, maybe with shortcuts triggers more likely.  

**Expected behavior**

**Screenshots**
![Captura de pantalla de 2021-02-22 23-52-54](https://user-images.githubusercontent.com/6747912/108780899-5d2a4800-7569-11eb-8250-ab8483e29c8b.png)

,                                h                 v
            b                                                         8                                                             )
                      u                                               R                                                                          
                      I                                corrupted size vs. prev_size
                                                                                   Abortado (`core' generado)

**Additional context**
 CMatrix version 1.2a by Chris Allegretta (compiled 00:00:00, Jul 27 2020)

linked to the resize bug I saw years ago somewhere?

**Comment by abishekvashok** [comment]
> CMatrix version 1.2a by Chris Allegretta (compiled 00:00:00, Jul 27 2020)

Can you test v2.0 ? Or maybe the development branch? Please do let me know how it works as I remember solving a suimilar bug years ago.

**Comment by Cristo-Conklin** [comment]
Funny how updated fedora uses so obsolete versions, I didn't realize.

Will try 2.0 and let you know, as it happens randomly.

Thanks, ser. Namaskar
