### ISSUE TITLE
desktop file uses htop icon

### ISSUE THREAD

**Issue by Un1q32** [abishekvashok/cmatrix#141]
**Describe the bug**
The .desktop file packaged with the version in the ubuntu is configured to use the htop icon.

**To Reproduce**
Install the version of cmatrix in the ubuntu repos, and edit the .desktop file in /usr/share/applications/.  You will find the icon it is set to use is htop, rather than cmatrix.

**Expected behavior**
The .desktop file should use cmatrix as the icon name rather than htop.

**Screenshots**

 - OS: [e.g. iOS] Ubuntu
 - Version [e.g. 22] latest (as of writing this)

**Additional context**

**Comment by abishekvashok** [comment]
Hey I don't have access to the cmatrix used in the ubuntu repos. The code is pulled by from this repo but I don't know if they'll see this and update the icon. Closing this hence. I'll see what I can do though. Thanks for raising this issue :)
