### ISSUE TITLE
cmatrix showing different background

### ISSUE THREAD

**Issue by tsjazil** [abishekvashok/cmatrix#143]
![1643377474](https://user-images.githubusercontent.com/45793120/151557652-e785c9de-d222-49ae-bcdb-d64c0566512a.jpg)

**Comment by abishekvashok** [comment]
Will you please be able to give little bit more info, like the version used, test environment, reproduction steps, etc. so I could try debugging this...

**Comment by tsjazil** [comment]
I m using alacritty and i changed colour scheme a little bit

**Comment by tsjazil** [comment]
Sorry its a problem in my side

**Comment by abishekvashok** [comment]
It's okay. Thanks for taking your time to look into it :)

**Comment by tsjazil** [comment]
Problem is that my background color and color assigned to black are not same And cmatrix is using color assigned to black as its bg

**Comment by DPatel0211** [comment]
Where is the configuration file so that I can edit the background color cmatrix uses while running? I'm looking to have it transparent so that it complies with my terminal background instead of the assigned black value.

**Comment by tsjazil** [comment]
ig there is no cmatrix config file i edited my terminals bg to match with black color
