### ISSUE TITLE
CMake build system

### ISSUE THREAD

**Issue by hoijui** [abishekvashok/cmatrix#15]
hey! :-)
i made a first, tiny step in that direction (supporting building with CMake):
https://github.com/hoijui/cmatrix/commits/cmake

it configures and compiles fine on my system (Ubuntu 14.04 64bit), and the resulting `cmatrix` executable seems to work fine.
what it does not do, is anything else then compiling the executable, like.. doing anything with the font, for example. what other things would be required for it to have the same functionality/features as the current build system?

**Comment by abishekvashok** [comment]
The fonts are our only distributable except the compiled cmatrix file which goes in $prefix or /use/bin/.
 When you are done, or now make a PR, so that we can get into that easily ther rin the PR.

**Comment by abishekvashok** [comment]
@hoijui any updates? Can we safely close this?

**Comment by hoijui** [comment]
yep, all done! :-)
