### ISSUE TITLE
Make fails with fatal error

### ISSUE THREAD

**Issue by BigBobDalton** [abishekvashok/cmatrix#159]
Cannot install make fails with the following code;

Installation instruction 1 fails sudo autoreconf -I

configure.ac:6: installing './missing'

configure.ac:18: installing './compile'
configure.ac:8: installing './config.guess'
configure.ac:8: installing './config.sub'
configure.ac:6: installing './install-sh'
configure.ac:6: installing './missing'
Makefile.am: installing './depcomp'

sudo make

make  all-am
make[1]: Entering directory '/cmatrix-master'
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT cmatrix.o -MD -MP -MF .deps/cmatrix.Tpo -c -o cmatrix.o cmatrix.c
cmatrix.c:56:20: fatal error: curses.h: No such file or directory
 #include <curses.h>
                    ^
compilation terminated.
Makefile:437: recipe for target 'cmatrix.o' failed
make[1]: *** [cmatrix.o] Error 1
make[1]: Leaving directory '/home/Bob/cmatrix-master'
Makefile:327: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by abishekvashok** [comment]
Do you have ncurses installed? Did you run `./configure` (the script generated by autoreconf) ? If so, please re-open.

**Comment by BigBobDalton** [comment]
Yes, I have ncurses installed and I ran ./configure, it fails as well. The error fails at configure.ac.6-

Thanks for closing before checking.  Great idea.  I won't re-open, instead I will just do without.
