### ISSUE TITLE
exit on first keystroke should print the keystroke on the terminal

### ISSUE THREAD

**Issue by pberto** [abishekvashok/cmatrix#25]
The -s: option activates the "Screensaver" mode, with exits on first keystroke.
This is nice but the keystroke is not recorded on the terminal. So if for example user wants to type "git" the  first character `g` should be recorded and when learning the screen from matrix, g should be present on the terminal along with whatever other characters the user has typed.

**Comment by abishekvashok** [comment]
That seems an ideal feature...

**Comment by livibetter** [comment]
I've never thought of this, and thanks to [hstr][], the only program that I know that can do this, it needs that, so user can edit command in shell prompt and execute command by the shell.

After found out how hstr does it, I wrote the following piece of code:

[hstr]: https://github.com/dvorka/hstr

```c
                ungetch(keypress);

                char *buf = malloc(1);
                char *p = buf;
                while ((*p++ = wgetch(stdscr)) != ERR) {
                    buf = realloc(buf, sizeof(buf) + 1);
                }
                *(p - 1) = 0;

                p = buf;
                while (*p) {
                    ioctl(0, TIOCSTI, p++);
                }
                free(buf);
```

Put them before `finish()`:

https://github.com/abishekvashok/cmatrix/blob/93fd3575a04b61e8b7fbc227de9c91891bd9a085/cmatrix.c#L477-L479

The code can be reduced down to one line if we only consider human typing or single character, the code above will make sure whatever in standard input will be carried over via `TIOCSTI` (simulating typed input), a single char or a whole bunch of text, for instance, user pastes a text.

`TIOCSTI` is likely the simplest way to achieve the feature—if there is even a possibility of having other methods—I was baffled by how a process could put stuff in standard input after it's gone, that just doesn't seem possible unless you have help from outside.  Before reading hstr's code, I thought it must employ some wrapper with some secret Bash/shell functionality that I am not aware of, but nope.  Its solution is just that `ioctl` line.

While trying to read about the magic of `TIOCSTI`, I stumbled [On the Insecurity of TIOCSTI](http://undeadly.org/cgi?action=article&sid=20170701132619).  We will need more code to turn it back on for those systems, if that is possible, although Linux wouldn't be one of them.

Nonetheless, do we actually need this feature for not being able to press an extra key that is destined to be forgotten?  Frankly, I would vote against this feature, it's cool, but not worth all the extra codes in my opinion.

**Comment by abishekvashok** [comment]
>I was baffled by how a process could put stuff in standard input after it's gone

We can do that just before exiting after the terminal has been cleared. It's really easy.

**Comment by abishekvashok** [comment]
Pass an argument (character) to finish. See the screensaver switch case inside the on character press selection section.

**Comment by livibetter** [comment]
@abishekvashok then you should be the one to do it.

----

This issue got me a thought, if we would be doing this, why not go all the way, that is [mouse as well][m].  The `-s` screensaver mode should also exit upon any mouse activities.  CMatrix be a real screensaver!

But again, against it, because more codes, that's why I am not opening a feature request, @abishekvashok or anyone think it's good, it's your issue to open.

[m]: http://tldp.org/HOWTO/NCURSES-Programming-HOWTO/mouse.html

**Comment by AstolfoKawaii** [comment]
Pull request #67 implements this functionality.

**Comment by kovasap** [comment]
This feature does not seem to work when building with cmake at head.  Anyone else have this problem?
