### ISSUE TITLE
load font in macOS ?

### ISSUE THREAD

**Issue by Moonbeam4520** [abishekvashok/cmatrix#27]
when i use -l option, the font does not display properly. Is there a way to force loading a compatible font ?
<img width="1440" alt="capture d ecran 2017-11-29 a 21 44 28" src="https://user-images.githubusercontent.com/16178951/33410487-7d44bcb0-d54e-11e7-9f81-120bc64487b1.png">

**Comment by abishekvashok** [comment]
@Joel-Costamagna currently the font is installe donly on linux, I will check for a solution on macOS.

**Comment by abishekvashok** [comment]
Going to close this. Would open seperate issue for ports compatibility of fonts.
