### ISSUE TITLE
Program crashes unexpectedly when resized to be too small

### ISSUE THREAD

**Issue by goosehub** [abishekvashok/cmatrix#3]
To recreate, begin program, and make window as small as possible. Program will crash. Obviously not a big deal, but thought I'd let you know. Thanks for building this. I use it way more often than I should.

**Comment by abishekvashok** [comment]
Let me know on https://github.com/abishekvashok/cmatrix if this still exists @goosehub

**Comment by goosehub** [comment]
@abishekvashok  Is that repo the same as what I get in Ubuntu with `sudo apt-get install cmatrix`?

**Comment by abishekvashok** [comment]
@goosehub yes. However in the development branch I am currently updating automake.

**Comment by abishekvashok** [comment]
@goosehub Chris just handled me the key of in charge so I am currently on it, can you pls check if the issue exists and file a bug report if it does'nt: https://github.com/abishekvashok/cmatrix

**Comment by abishekvashok** [comment]
Bug is tested and has been found to be alive
More specifications and info:

Error name: `floating pointer error`
Error happens when number of lines in a console goes below 4.
