### ISSUE TITLE
Migrate to setenv

### ISSUE THREAD

**Issue by abishekvashok** [abishekvashok/cmatrix#38]
I am submitting a feature

### Problem or Feature in Brief

putenv is used in the code. Although it was the standard in the past, now we have setenv which is also a part of the standard and is more stable. Considering that fact that various putenv bugs still exist ee should migrate to setenv.
### 

### Solution (if any)

Change putenv to setenv

### Would you like to work on it?

I can do that if no one wants to do so in the next 5 days.

**Comment by abishekvashok** [comment]
It need not to be a single person. Multiple people can do this. Also this is not priority.

**Comment by livibetter** [comment]
It should be really easy, just remove a few lines and edit one, but I am not doing it as I suspect your intention that @abishekvashok  didn't do it right away with this issue.

So a suggestion: You should also put on `help-wanted` label, and remove it and assign the issue when 5-day time is due and starting to work on it by yourself.

**Comment by livibetter** [comment]
In case someone wants to do it, here is the relevant piece:

https://github.com/abishekvashok/cmatrix/blob/93fd3575a04b61e8b7fbc227de9c91891bd9a085/cmatrix.c#L748-L752

But not limited to here, code as needed as we wouldn't need one of the variables.
