### ISSUE TITLE
make on ubuntu 14.04 fails - AM_INIT_AUTOMAKE: two- and three-arguments forms are deprcated

### ISSUE THREAD

**Issue by rcampbel3** [abishekvashok/cmatrix#4]
Hi, after doing a source checkout, I'm able to complete ./configure, but when I run make, I get the following:

looks like you may need to 'modernize' your 'configure.ac' as follows:
https://www.gnu.org/software/automake/manual/html_node/Public-Macros.html

~/project/cmatrix $ make
cd . && aclocal
aclocal: warning: autoconf input should be named 'configure.ac', not 'configure.in'
cd . && automake --gnu --include-deps Makefile
automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'
configure.in:3: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated.  For more info, see:
configure.in:3: http://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation
configure.in:7: error: required file './compile' not found
configure.in:7:   'automake --add-missing' can install 'compile'
Makefile.am: error: required file './ChangeLog' not found
Makefile.am: error: required file './depcomp' not found
Makefile.am:   'automake --add-missing' can install 'depcomp'
automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'
make: *** [Makefile.in] Error 1

**Comment by ik0r** [comment]
Sorry, this is just a source code mirror here.

And maybe you can install cmatrix from linuxbrew?

**Comment by abishekvashok** [comment]
@rcampbel3 instead of `make` pls run `automake --gnu --include-deps Makefile --add-missing` it will create dummy files.

The source code has been moved to https://github.com/abishekvashok/cmatrix

**Comment by abishekvashok** [comment]
Ok since the repo ha seen transferred. I am updating the code.

**Comment by abishekvashok** [comment]
Solved it in https://github.com/abishekvashok/cmatrix/commit/476808fe193cecc0d8086923c2c57c21793810f4

@rcampbel3 pls try the new release :)
