### ISSUE TITLE
Template [INSERT EMAIL ADDRESS] in Contributing.md

### ISSUE THREAD

**Issue by an0rak-dev** [abishekvashok/cmatrix#45]
I am submitting a Bug Report

### Problem or Feature in Brief
In the Contributing.md, there is still a [INSERT EMAIL ADDRESS] in the Enforcement part.

### 

### Would you like to work on it?
no

**Comment by abishekvashok** [comment]
Fixes via https://github.com/abishekvashok/cmatrix/commit/94e63cd5aac72e6ebeede5589e0d936d0b0e0d9b
