### ISSUE TITLE
Crashes when terminal is less than 2 lines high

### ISSUE THREAD

**Issue by ghost** [abishekvashok/cmatrix#47]
I am submitting a bug report.

When  cmatrix is running, and the terminal is resized to less than two lines, cmatrix crashes with the following error:

`996 floating point exception  cmatrix`

To fix it, I suggest cleanly exiting when the terminal is too small, rather than crashing. I can add a quick solution to prevent a harsh exit, however further investigation may be required to find the source of the error.

**Comment by tansly** [comment]
I cannot reproduce this. Looks like it was fixed in #8. 

Can this be closed?

**Comment by abishekvashok** [comment]
Yep this can be closed
