### ISSUE TITLE
Please tag another higher version of cmatrix

### ISSUE THREAD

**Issue by hosiet** [abishekvashok/cmatrix#59]
I am submitting a  Feature Request

### Problem or Feature in Brief
The version number of cmatrix in Debian GNU/Linux, Ubuntu and other deb-based
distributions was "1.2a", which is higher than current release on GitHub (1.2).
We need a higher version number to cleanly update the package.

### Solution (if any)
Tag another release on the appropriate commit that is equal or later than current
1.2 tag.

Since the freeze of next Debian major release will take place on 12 February 2019, I suggest
we tag the release as early as possible and no later than that day.

**Comment by abishekvashok** [comment]
Moving to `2.0` now!

**Comment by hosiet** [comment]
Thanks! I will package it in Debian later.

Since we have already missed the freeze deadline for Debian, the next upload in Debian will be postponed till after the release of Debian 10.
