### ISSUE TITLE
Source code has been moved

### ISSUE THREAD

**Issue by abishekvashok** [abishekvashok/cmatrix#6]
I've taken up cmatrix from Chris.
So pls update your indices to: https://github.com/abishekvashok/cmatrix

**Comment by ik0r** [comment]
👏👏👏
I will put a BIG notice on this repo to redirect visitor to your one. Or maybe I can transfer this repo to you directly

Wish cmatrix can have good development !

**Comment by ik0r** [comment]
If you accept transfer please let me know. otherwise I will update README to add a BIG notice.

I think the best solution is transfer this repo to you , because many users had stared this repo

**Comment by abishekvashok** [comment]
That might come in collision. I would try to accept it.

**Comment by ik0r** [comment]
I transfered but failed. Because you already have a same name repo

**Comment by abishekvashok** [comment]
I am deleting that. I would take this repo and update the root commit with the files from there.
Pls initiate one @Treri

**Comment by ik0r** [comment]
@abishekvashok please accept

**Comment by abishekvashok** [comment]
Done closing this issue.
