### ISSUE TITLE
Cmatrix core dumps when resizing terminal window

### ISSUE THREAD

**Issue by cole-rogers** [abishekvashok/cmatrix#63]
I am submitting a  Bug Report

### Problem or Feature in Brief

Cmatrix core dumps when resizing the terminal window too much

Tested on GNOME terminal and tilix
### 

### Solution (if any)

Dont.

### Would you like to work on it?

no

**Comment by tansly** [comment]
Hello there! Can you check which version of cmatrix you are running? `cmatrix -V` should do. If you are running your distro version, note that most distros use a pretty old version.

I'm asking because this issue should have been fixed in #26. If your version includes that fix and still has this error, I may look into it again to see if I'm missing anything.

Thanks!

**Comment by tansly** [comment]
Just checked and I see that the issue persists. Interesting.

**Comment by tansly** [comment]
> Just checked and I see that the issue persists. Interesting.

Maybe not. I can't seem to reproduce it with the latest master no matter what I do. I'm beginning to think that I had run the wrong version when I reproduced it. Anyone else here who can reproduce this? Better with a core dump.

**Comment by cole-rogers** [comment]
> Hello there! Can you check which version of cmatrix you are running? `cmatrix -V` should do. If you are running your distro version, note that most distros use a pretty old version.
> 
> I'm asking because this issue should have been fixed in #26. If your version includes that fix and still has this error, I may look into it again to see if I'm missing anything.
> 
> Thanks!

CMatrix version 1.2 (compiled 12:43:58, Oct  6 2018)

Tested on arch.

**Comment by cole-rogers** [comment]
Hmm the error it gave just now was floating point exception (core dumped)

**Comment by abishekvashok** [comment]
@retiform can you check it with the latest version on master?

**Comment by cole-rogers** [comment]
@abishekvashok yes it appears to be impossible to crash now via this method. I think this can be closed. Consider releasing a new version soon?

**Comment by abishekvashok** [comment]
Yep in late march
