### ISSUE TITLE
cmatrix -l blank screen

### ISSUE THREAD

**Issue by chowbok** [abishekvashok/cmatrix#64]
In a linux text console, running cmatrix -l just gives me a blank screen. "cmatrix" by itself runs fine.

I'm running on Arch Linux. I tried copying matrix.fnt and matrix.psf.gz to $PWD but the behavior is the same. My TERM is "linux" and my LANG is en_US.UTF-8 (but I tried setting my LANG to "ISO-8859-1" and also to "C"; neither fixed the issue). ncurses is 6.1. kbd is 2.0.4. My default console font is ter-v14n. If I do "setfont matrix", it changes the font to the matrix font correctly. 

Kinda stumped here. Let me know if there's any other information you need, or anything else I can try.

**Comment by AstolfoKawaii** [comment]
I think it because cmatrix was compiled without HAVE_CONSOLECHARS option, maybe you should try to use cmatrix with #72 pull request (commit 96948ced7ccb7bbdd4e992e31bbce23b85f636bf) merged and if you see 'Unable to use both "setfont" and "consolechars".', i am right.
