### ISSUE TITLE
i get this error 

### ISSUE THREAD

**Issue by Brockmerkwan** [abishekvashok/cmatrix#7]
╭─cybernecro@cybernecro-MS-7850 ~/Desktop  
╰─➤   cmatrix -lba
Couldn't get a file descriptor referring to the console

I installed it via apt. I tried to clone install your version, however, i could not get it to make install.

**Comment by abishekvashok** [comment]
Hi @Brockmerkwan.

That's because `-l`works only on tty with console fonts

So, pls run it with the `-l` argument only when you are in a tty or set the font for the terminal to be `matrix.psf` by running `setfont matrix.psf` while being in the source directory.

**Comment by abishekvashok** [comment]
Would improve the error message.

**Comment by abishekvashok** [comment]
Duplicate of #1
