### ISSUE TITLE
Try running "setfont matrix" by hand

### ISSUE THREAD

**Issue by aquaductape** [abishekvashok/cmatrix#85]
I installed cmake by cloning and using the `configure` route. Cmake works unless I run with the -l argument `cmake -lba` and I get this error.
```
Couldn't get a file descriptor referring to the console
There was an error running setfont. Please make sure the
setfont program is in your $PATH.  Try running "setfont matrix" by hand.
```
My setfont is in $PATH which is inside `/bin` so that's fine.

I don't understand what I should do with the instruction `setfont matrix by hand`, I ran `setfont matrix` and `setfont matrix.fnt` and both returned `Couldn't get a file descriptor referring to the console`.

My device 
```
elementary OS 5.0 Juno
Built on Ubuntu 18.04.2 LTS
Linux 4.15.0-58-generic
GTK+ 3.22.30
```

**Comment by abishekvashok** [comment]
Hey, thanks for reaching out!

setfont returns the above error messages when you have some setfont command in your .bashrc, .bash_profile, .bash_login, .profile or /etc/profile.

Otherwise, look for something else that may be accessing the console.

Hope that helps :)

**Comment by aquaductape** [comment]
No luck so far, I did a search at my home directory to see if there were any setfont commands 

`grep -Hrn --exclude-dir={.cache,.vscode,Documents} --exclude={.zsh_history,.viminfo} setfont .` Search excludes directories of cache, vscode(only py files popped up and most likely variable names), and Documents. Excludes files .zsh_history and viminfo which are logging files.

Only this shows up 
```
Binary file ./.config/google-chrome/Default/Shortcuts matches
Binary file ./.config/google-chrome/Default/Local Storage/leveldb/000099.ldb matches
Binary file ./.config/google-chrome/Default/Local Storage/leveldb/000101.ldb matches
Binary file ./.config/google-chrome/Default/Local Storage/leveldb/000093.ldb matches
Binary file ./.config/google-chrome/Default/Local Storage/leveldb/000100.log matches
Binary file ./.config/google-chrome/Default/Local Storage/leveldb/000096.ldb matches
Binary file ./.config/google-chrome/Default/Favicons matches
Binary file ./.config/google-chrome/Default/History matches
Binary file ./.config/google-chrome/Default/Last Tabs matches
Binary file ./.config/google-chrome/Default/History Provider Cache matches
Binary file ./.config/google-chrome/Default/Session Storage/000216.ldb matches
Binary file ./.config/google-chrome/Default/Session Storage/000221.ldb matches
Binary file ./.config/clipped/ClipboardStore.sqlite matches
Binary file ./.vim_runtime/temp_dirs/undodir/%etc%profile matches
Binary file ./.vim_runtime/temp_dirs/undodir/%home%caliber%.zshrc matches
Binary file ./.vim_runtime/temp_dirs/undodir/%home%caliber%.bashrc matches
```

I also changed the font in tty with `setfont matrix` which did change the font in tty console but didn't solve the issue with cmatrix

**Comment by aquaductape** [comment]
Hold up, is the only way to run `cmatrix -l` is in tty? Because this whole time I've been trying to do it in a regular terminal

**Comment by abishekvashok** [comment]
> Hold up, is the only way to run cmatrix -l is in tty? Because this whole time I've been trying to do it in a regular terminal

Yes!

**Comment by SturmB** [comment]
Please forgive me for my lack of knowledge, but isn't a terminal the same thing as a tty? What's the difference? And how does one run cmatrix in a tty, then?

**Comment by space-pagan** [comment]
@SturmB A terminal emulator and a tty are not the same, as a term emulator uses libX11 api calls (or indirectly through some other api), while a tty is a direct connection to the serial console hardware device. `setfont` only works inside the tty, and `consolechars` is deprecated. 

As far as HOW to run cmatrix in the tty, just like any other program. If you aren't sure how to get to to the tty, it's usually through the `CTRL+ALT+F#` key combination, although I would recommend that you consult your distribution's wiki for more specifics.

@aquaductape @abishekvashok This issue should be closed.

**Comment by mgage-nsheridan** [comment]
Should I dare to say that maybe could we get this working in a non TTY setting?  Tons of people on linux and mac kind of want it to work normally in iterm2 or terminal, vs connecting via screen to a TTY or whatever, i dont even understand fully how this is an explnation. (i.e. "it  DOES work, just not anywhere where anyone normal would ever want to use it")
