### ISSUE TITLE
install on macOs

### ISSUE THREAD

**Issue by spl1nt3r99** [abishekvashok/cmatrix#88]
Hi there, how can I install this on mac?

**Comment by evilr00t** [comment]
@Pro100Denysko you can use homebrew (http://brew.sh). 
Then you should type: `brew install cmatrix` Enjoy 💯 

Edit: brew has old version - altho I was able to compile the new one. I'll try to write a tap for the new one.

**Comment by birdybro** [comment]
What evilr00t said.

http://macappstore.org/cmatrix/

Decent mac site that quickly answers questions like this in the future.

**Comment by spl1nt3r99** [comment]
@evilr00t Yeah, thanks

**Comment by evilr00t** [comment]
PR for upgraded version: https://github.com/Homebrew/homebrew-core/pull/46045
