### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by Prince213** [abishekvashok/cmatrix#94]
I am submitting a Feature Request.

### Feature in Brief
Make cmatrix compiles and runs on native Windows.

### Solution (sort of)
[cmatrix.c.patch.gz](https://github.com/abishekvashok/cmatrix/files/3934869/cmatrix.c.patch.gz)
This patch is based on the [latest commit](https://github.com/abishekvashok/cmatrix/commit/c15d24a656d3ca4087c95253267807f41e26b686). And the patched source can be compiled and linked against [PDCurses](https://github.com/wmcbrine/PDCurses)(and probably other curses libraries like ) using this command: `gcc -DVERSION="2.0" -I/path/to/pdcurses/include/dir/ cmatrix.c /path/to/pdcurses.a`. This patch is not complete but it makes basic features work.

### Would you like to work on it?
yes :)

**Comment by abishekvashok** [comment]
Go on :)

**Comment by gerroon** [comment]
Hi

I am trying to compile this under Mingw64 but I am getting

```
make[1]: Entering directory '/tmp/cmatrix'
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT cmatrix.o -MD -MP -MF .deps/cmatrix.Tpo -c -o cmatrix.o cmatrix.c
cmatrix.c:32:10: fatal error: termios.h: No such file or directory
   32 | #include <termios.h>
      |          ^~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:433: cmatrix.o] Error 1
make[1]: Leaving directory '/tmp/cmatrix'
make: *** [Makefile:317: all] Error 2


```

**Comment by abishekvashok** [comment]
> I am trying to compile this under Mingw64

Mingw isn't fully complaint with POSIX afaik - hence the error. Try giving a go with Cygwin (POSIX complaint)

**Comment by Prince213** [comment]
Update: see [here](https://github.com/Prince213/cmatrix).
@gerroon try this. Does it work?

**Comment by abishekvashok** [comment]
Seems good, can you make a pull?

**Comment by Prince213** [comment]
PR is at [here](https://github.com/abishekvashok/cmatrix/pull/102).

**Comment by abishekvashok** [comment]
Merged!
