### ISSUE TITLE
Redundant line in cmatrix.c

### ISSUE THREAD

**Issue by tnaia** [abishekvashok/cmatrix#95]
I am submitting a Bug Report

### Brief

Line 608 of `cmatrix.c` has a redundant assignment (see below from lines 606 to 609 inclusive).

``` c
if (matrix[0][j].val == -1 && matrix[1][j].val == ' '
    && spaces[j] > 0) {
    matrix[0][j].val = -1;
    spaces[j]--;
```
### 

### Solution (if any)
Just remove line 608 (`matrix[0][j].val = -1;`).

### Would you like to work on it?
Yes! (Never made a pull request in life, but would love to learn! Can I make one?)

**Comment by abishekvashok** [comment]
Yeah you can make one :)

**Comment by tnaia** [comment]
Thanks! Done.

**Comment by abishekvashok** [comment]
I've merged it! Thanks for contributing!
