### ISSUE TITLE
Graphical issues when resizing the terminal window

### ISSUE THREAD

**Issue by StavromulaBeta** [abishekvashok/cmatrix#98]
I am submitting a bug report

### Problem or Feature in Brief

When I expand the terminal window with cmatrix running, the screen clears, and then cmatrix continues but confined to the previous window size.
When I shrink the terminal window, there are block characters left on the terminal that don't go away.
https://imgur.com/a/Bq88pPq
This occurs in xterm. I have just tested urxvt also. In urxvt, cmatrix will expand to fit when the window is expanded, but there are still block characters when I shrink the window.
### 

### Solution (if any)

Perhaps just basically restarting the entire program as well as clearing the screen when the window is resized?
### Would you like to work on it?

Uh... I can try.

**Comment by nabbi** [comment]
I am also seeing this in version 2.0, original version 1.2a resizes correctly.

XTerm 351
ncurses 6.2

#108 appears to be a duplicate report. Thank you.

**Comment by space-pagan** [comment]
Did you compile with autotools, or cmake? the current cmake directive skips a good majority of the flags that are expected (I'm working on it)

**Comment by xlucn** [comment]
Just tested two build method on the latest git, both give the color blocks, only the one build with cmake does not resize with terminal.

**Comment by space-pagan** [comment]
Can you show a screenshot of what you mean by "color blocks"? Additionally, could you try my [fork](https://github.com/space-pagan/cmatrix) and let me know if you get the same issue (with color blocks, I haven't fixed the cmake resize issue yet so I *know* that's still broken)

**Comment by xlucn** [comment]
With cmatrix in this repo:
edit: P.S. the color is color8 in base16 colors (the brighter dark color?)
edit again: tested with gnome-terminal, urxvt, termite and st
![cmatrix-background-issue](https://user-images.githubusercontent.com/12032219/101622081-9286c580-3a51-11eb-909c-6b356d3bd974.gif)
With your fork, it's `~`, but still the same problem I think:
![cmatrix-background-issue-fork](https://user-images.githubusercontent.com/12032219/101622159-a8948600-3a51-11eb-8127-c8f85ca7c6eb.gif)

**Comment by space-pagan** [comment]
Cool. I'll try to figure out where the `~`'s are coming from.

**Comment by abishekvashok** [comment]
Hey guys, so I kinda got a fix, it's because head isn't correctly set. have made a pr, test it out:


![](https://im6.ezgif.com/tmp/ezgif-6-cdb4275d1d6d.gif)

**Comment by space-pagan** [comment]
> Hey guys, so I kinda got a fix, it's because head isn't correctly set. have made a pr, test it out:

This doesn't fix the fact that people can't resize at all when compiling with CMake.

**Comment by abishekvashok** [comment]
> This doesn't fix the fact that people can't resize at all when compiling with CMake.

Nope, you are right it doesn't! both are different issues ~ I guess

**Comment by StavromulaBeta** [comment]
This does fix most of the colour blocks, but I am still getting  a single line of blocks at the bottom of the screen. I only see this when shrinking the window. I guess this could be to do with how characters are handled when they reach the bottom of the screen.

**Comment by xlucn** [comment]
I tried the counting 1<=i<=LINES, I don't know what it means but there seems to be no blocks at the bottom.

**Comment by abishekvashok** [comment]
> This does fix most of the colour blocks, but I am still getting a single line of blocks at the bottom of the screen. I only see this when shrinking the window. I guess this could be to do with how characters are handled when they reach the bottom of the screen.

Some non-printable characters are reaching the bottom of the screen, we are somehow trying to print them and it doesn't help, I updated the PR; can you check if it works now?
